// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package oidc.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GenerateJWT extends CustomJavaAction<java.lang.String>
{
	private java.lang.String jwk;
	private oidc.proxies.ENU_SigningAlgorithm algorithm;
	private IMendixObject __jwt;
	private oidc.proxies.JWT jwt;
	private java.lang.String secret;

	public GenerateJWT(IContext context, java.lang.String jwk, java.lang.String algorithm, IMendixObject jwt, java.lang.String secret)
	{
		super(context);
		this.jwk = jwk;
		this.algorithm = algorithm == null ? null : oidc.proxies.ENU_SigningAlgorithm.valueOf(algorithm);
		this.__jwt = jwt;
		this.secret = secret;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.jwt = this.__jwt == null ? null : oidc.proxies.JWT.initialize(getContext(), __jwt);

		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GenerateJWT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
